apiVersion: route.openshift.io/v1
kind: route
matadata:
  labels:
    app: todonodejs
    name: frontend
  name: frontend
spec:
  host: todo.apps.ocp4.example.com
  path: "/todo"
  to:
    kind: service
    name: dev-frontend
    weight: 100
  wildcardPolicy: None
